leftnav:
- identifier: 0d1e32fa-3802-572f-3982-4cb1a2ad2051
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 52ae3b7b-b127-221d-d64e-e65946b367f2
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 9b1fef34-bca8-d2fd-933e-cdf7ad77f6ed
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 64082b79-35f2-3000-2707-edcc677f062d
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: d9d424d3-7bca-a195-6954-21acbf6b45da
  name: Exams
  pageRef: /pages/exams
  weight: 50
